trigger:
  branches:
    include: [master, test-*]
  tags:
    include: ["*"]

resources:
  repositories:
    - repository: aleksac
      type: github
      endpoint: AleksaC
      name: AleksaC/azure-pipelines-templates
      ref: refs/tags/v0.0.2

jobs:
  - template: jobs/pre-commit.yml@aleksac
